DROP DATABASE IF EXISTS ACOES;
CREATE DATABASE ACOES;

DROP TABLE IF EXISTS ACAO;
CREATE TABLE ACAO(
id  INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
nome_empresa VARCHAR (50) NOT NULL,
ticket VARCHAR (6) NOT NULL,
segmento VARCHAR (100) NOT NULL
);

DROP TABLE IF EXISTS COMPRAS;
CREATE TABLE COMPRAS(
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
id_acao INT NOT NULL,
valor FLOAT (10) NOT NULL,
quantidade INT (10) NOT NULL,
data_compra DATE
);
 
 DROP TABLE IF EXISTS PRECO_MEDIO;
 CREATE TABLE PRECO_MEDIO(
 id_acao INT NOT NULL,
 id_compras INT NOT NULL
  );


-- CONSTRAINTS

ALTER TABLE PRECO_MEDIO ADD FOREIGN KEY(id_acao) REFERENCES ACAO(id);
ALTER TABLE PRECO_MEDIO ADD FOREIGN KEY(id_compras) REFERENCES COMPRAS(id);
ALTER TABLE COMPRAS ADD FOREIGN KEY (id_acao) REFERENCES ACAO(id);
